FROM python:3.10-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir flwr torch

# Copy server code and models
COPY fl_implementation/server.py .
COPY models/ ./models/

CMD ["python", "server.py"]
