FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir flwr pandas numpy scikit-learn torch

COPY fl_implementation/server.py fl_implementation/server.py
COPY models/ models/
# Ensure schemas directory exists
RUN mkdir -p schemas fl_implementation

ENV PYTHONPATH=/app
CMD ["python", "fl_implementation/server.py"]
